In [ ]:
import pandas as pd

# Creazione del dataframe(dati) = dataset(Tabella)
data = {
    "nome": ["Filippo", "Salomon", "Asia", "Ana"],
    "cognome": ["Battaglia", "Rossi", "Verdi", "Neri"],
    "voto": [8, 10, 9, 7]
}

df = pd.DataFrame(data) # chiama pandas e crea un dataframe con i dati 

df

      nome    cognome  voto
0  Filippo  Battaglia     8
1  Salomon      Rossi    10
2     Asia      Verdi     9
3      Ana       Neri     7

Fitrare dati

In [4]:
df[df["voto"] > 8]

      nome cognome  voto
1  Salomon   Rossi    10
2     Asia   Verdi     9

Calcolare media

In [5]:
df["voto"].mean()

np.float64(8.5)

Aggiungere una colonna

In [7]:
df["Promosso"] = df["voto"] > 8
df

      nome    cognome  voto  Promosso
0  Filippo  Battaglia     8     False
1  Salomon      Rossi    10      True
2     Asia      Verdi     9      True
3      Ana       Neri     7     False

Ordinare

In [ ]:
df.sort_values(by="voto", ascending=False)
df

      nome    cognome  voto  Promosso
0  Filippo  Battaglia     8     False
1  Salomon      Rossi    10      True
2     Asia      Verdi     9      True
3      Ana       Neri     7     False

In [ ]:
df.sort_values(by="voto", ascending=False)
df

      nome    cognome  voto  Promosso
1  Salomon      Rossi    10      True
2     Asia      Verdi     9      True
0  Filippo  Battaglia     8     False
3      Ana       Neri     7     False

Esercizio 1: 
    Creare 1 data frame corso con 4 colonne(nomeCorso, descrizione, dataInizio, dataFine) e stampare il contenuto

Esercizio 2:
    Creare il secondo data frame (studenti) con 4 colonne(nome, cognome, dataNascuita, email, telefono) e stampa i dati

In [ ]:
studenti = pd.DataFrame({
    "nome": ["Marco", "Camilla", "Alessio", "Barbara", "Andrea"],
    "cognome": ["Rossi", "Bianchi", "Verdi", "Neri", "Gialli"],
    "data_nascita": ["1990-01-01", "1992-05-15", "1991-08-20", "1993-12-10", "1990-03-25"],
    "email": ["marco.rossi@email.com", "camilla.bianchi@email.com", "alessio.verdi@email.com", "barbara.neri@email.com", "andrea.gialli@email.com"],
    "telefono": ["1234567890", "0987654321", "1122334455", "5566778899", "9988776655"]
})

studenti

      nome  cognome data_nascita                      email    telefono
0    Marco    Rossi   1990-01-01      marco.rossi@email.com  1234567890
1  Camilla  Bianchi   1992-05-15  camilla.bianchi@email.com  0987654321
2  Alessio    Verdi   1991-08-20    alessio.verdi@email.com  1122334455
3  Barbara     Neri   1993-12-10     barbara.neri@email.com  5566778899
4   Andrea   Gialli   1990-03-25    andrea.gialli@email.com  9988776655

In [ ]:
studenti.to_csv("studenti.csv", index=False) # to_csv è un metodo o funzione che permette di salvere un dataframe in un file .csv

In [20]:
corso = pd.DataFrame({
    "nomeCorso": ["Python Base", "Data Analysis", "Web Dev"],
    "descrizione": ["Corso base Python", "Analisi dati con pandas", "Sviluppo web"],
    "dataInizio": ["2024-01-10", "2024-02-01", "2024-03-01"],
    "dataFine": ["2024-02-10", "2024-03-01", "2024-04-01"]
})

corso

       nomeCorso              descrizione  dataInizio    dataFine
0    Python Base        Corso base Python  2024-01-10  2024-02-10
1  Data Analysis  Analisi dati con pandas  2024-02-01  2024-03-01
2        Web Dev             Sviluppo web  2024-03-01  2024-04-01

Salvataggio csv

In [ ]:
salva = corso.to_csv("corsi.csv", index=False)
if salva is None:
    print("Il salvataggio del file è andato a buon fine")
else:
    print("Attenzione: si è verificato un errore durante il salvataggio del file")

Salvataggio in Excel

In [22]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [25]:
salva = corso.to_excel("corsi_1.xlsx", index=False)
if salva is None:
    print("Il salvataggio del file è andato a buon fine")
else:
    print("Attenzione: si è verificato un errore durante il salvataggio del file")

Il salvataggio del file è andato a buon fine

In [33]:


studenti = pd.DataFrame({
    "nome": ["Marco", "Camilla", "Alessio", "Barbara", "Andrea"],
    "cognome": ["Rossi", "Bianchi", "Verdi", "Neri", "Gialli"],
    "data_nascita": ["1990-01-01", "1992-05-15", "1991-08-20", "1993-12-10", "1990-03-25"],
    "email": ["marco.rossi@email.com", "camilla.bianchi@email.com", "alessio.verdi@email.com", "barbara.neri@email.com", "andrea.gialli@email.com"],
    "telefono": ["1234567890", "0987654321", "1122334455", "5566778899", "9988776655"]
})

sal = studenti.to_excel("studenti.xlsx", index=False)
if sal is None:
    print("Il salvataggio del file è andato a buon fine")
else:
    print("Attenzione: si è verificato un errore durante il salvataggio del file")

Il salvataggio del file è andato a buon fine